[project]
name = "powerpress-podcast-fixer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dateparser>=1.2.1",
    "feedgen>=1.0.0",
    "lxml>=5.4.0",
    "requests>=2.32.3",
]
